version: "3"
services:

  psql:
    # todo надо затащить локалии в настройки для 4-й таски
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${POSTGRES_PORT_IN_HOST:-5432}:5432"
    volumes:
      - ./docker/psql:/var/lib/postgresql/data
      - ./docker/psql/init:/docker-entrypoint-initdb.d
    restart: always

  clickhouse:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - ./docker/clickhouse/chdata:/var/lib/clickhouse
      - ./docker/clickhouse/init:/docker-entrypoint-initdb.d
    ports:
      - "${CLICKHOUSE_PORT_IN_HOST:-8123}:8123"
